// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUyJMZmy36gq948DWk-MweF-UB3DkRons',
    appId: '1:358513304770:web:8cd72220d9ea0c1528075b',
    messagingSenderId: '358513304770',
    projectId: 'medibuddy-c6a05',
    authDomain: 'medibuddy-c6a05.firebaseapp.com',
    storageBucket: 'medibuddy-c6a05.appspot.com',
    measurementId: 'G-1LPSK3SL0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvlg9envGieYe5Lc8gaZP-N2mkz8su8A',
    appId: '1:358513304770:android:633b94728c1cb07228075b',
    messagingSenderId: '358513304770',
    projectId: 'medibuddy-c6a05',
    storageBucket: 'medibuddy-c6a05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVsZcoS3POV_eZPoPTseB6Re8B1FceNDs',
    appId: '1:358513304770:ios:8f78b4609961bd3728075b',
    messagingSenderId: '358513304770',
    projectId: 'medibuddy-c6a05',
    storageBucket: 'medibuddy-c6a05.appspot.com',
    iosClientId: '358513304770-g2v3intcuab3f6me5nhu4ua2ntiu1f4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.medibuddy',
  );
}
