// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63hnfcmHaiEVKdLy0nFymz9qPcKN4AdM',
    appId: '1:344815399063:web:15114d059e2d2c9808b9d2',
    messagingSenderId: '344815399063',
    projectId: 'medibuddy-8bee3',
    authDomain: 'medibuddy-8bee3.firebaseapp.com',
    databaseURL: 'https://medibuddy-8bee3-default-rtdb.firebaseio.com',
    storageBucket: 'medibuddy-8bee3.appspot.com',
    measurementId: 'G-FSDT3M3NL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqE0PmAhRAQwfn2YvAwVzredf6u6JtrTM',
    appId: '1:344815399063:android:d2a73627da48b7d608b9d2',
    messagingSenderId: '344815399063',
    projectId: 'medibuddy-8bee3',
    databaseURL: 'https://medibuddy-8bee3-default-rtdb.firebaseio.com',
    storageBucket: 'medibuddy-8bee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo9nnW-eU9ZRo4M6qIyHVks7-FEklfTc4',
    appId: '1:344815399063:ios:8ea02133d8fba9b008b9d2',
    messagingSenderId: '344815399063',
    projectId: 'medibuddy-8bee3',
    databaseURL: 'https://medibuddy-8bee3-default-rtdb.firebaseio.com',
    storageBucket: 'medibuddy-8bee3.appspot.com',
    iosClientId: '344815399063-7ng7olvnsejtgtf895fpmfpvnflln4vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.medibuddy',
  );
}
